### ISSUE TITLE
Publishing our images

### ISSUE THREAD

**Issue by 0xEAB** [dlang-dockerized/packaging#6]
We should (build and) publish our images to a registry of our choice.
And also on Docker Hub, if that isn’t the one of our choice.

#### Comments from Discord (*excerpt*)

> Using fully qualified image name is always preferred anyways, […]
– @Reavershark 

> Though the “what even is Podman?!” crowd would prolly not care
> I’ve never heard of *ghcr*, but I know *quay*. Everyone knows docker
– @0xEAB

**Comment by 0xEAB** [comment]
Looking for suggestions for suitable CI/CD services, too.

**Comment by kassane** [comment]
- CI suggestion:

https://github.com/kassane/docker-zig/blob/main/.github/workflows/ci.yml

Currently being able to adapt a basic docker-buildx example and install Zig toolchain (prebuilt) on several architectures.

I just needed to set the access tokens to docker Hub.

**Comment by jnms-me** [comment]
That uses zigup, which downloads a binary release.
We are building everything ourselves starting from only the system C/C++ compiler for several reasons.
Doing that in github actions will quickly hit usage limits I'm afraid.

**Comment by kassane** [comment]
> That uses zigup, which downloads a binary release.

Exactly! This is not bootstrap compiler build.

Although the main reason for this sharing is the use of GHA docker.

> We are building everything ourselves starting from only the system C/C++ compiler for several reasons.

The biggest difference in my [alpine-ldc2](https://github.com/kassane/alpine-ldc2-docker) repository, it is the fact that the pre-built packages from LLVM and the old ldc2.

(I remember that tried to use LLVM built by zig bootstrap, but ldc2 does not have **llvm-libcxx** support.
Seeking to avaliable targets support such as riscv64 without having pre-existing packages in Alpine.)

My biggest difficulty was to build aarch64 target using **docker-qemu** (_very slow_).

> Doing that in github actions will quickly hit usage limits I'm afraid.

Wouldn't it be viable to make binaries bootstrap available to shorten the build time?

**Comment by jnms-me** [comment]
> Wouldn't it be viable to make binaries bootstrap available to shorten the build time?

Sure, every CI job will only build a single image. The bootstrap compiler is only built once and then reused by other jobs.
But even that will stretch the limits of what github actions allows by default. At least it did when I tried it a year ago.

**Comment by 0xEAB** [comment]
Well, I don’t see CI/CD builds happen any time soon. (Would need a major sponsor for that – which is, nicely said, highly unrealistic.)
Nevertheless, I do plan to make the building at least semi-automatic. And I have a number of ideas regarding making it run in a clean system environment.

**Comment by 0xEAB** [comment]
- eaf61cce75466d655db677f42e72a8412c809300 – `./ddct namespace-copy` duplicates all tags from one “namespace” to another. This allows to generate repository+tag combos tailored to specific container registries for existing images.
- f190df2e169228965655c2cb17ccedeb48a7495f – `./ddct namespace-remove-all` removes all images within the configured “namespace”. This bug-fix commit changes the selector for the container_engine-rmi command from the ID to the specific tag. With the new namespacing features in-place, the old behavior did no longer make sense imho.
- d7e8f20b7448433dee82320aa5005516c2c97aa6 – `./ddct namespace-publish` assists with pushing images to container registries.

**Comment by 0xEAB** [comment]
ef177e101515721ae8d35b0f8b8d76aed6676976 – `./ddct build-selection` builds only a subset of images (plus their dependencies, of course). The subset can be composed from both a number of latest versions and a list of version specifiers; multiplied by the list of base-images.

**Comment by 0xEAB** [comment]
I’ve written a shell + GHA workflow that launches a cloud-server to build and push container-images.
→ https://github.com/dlang-dockerized/images

**Comment by 0xEAB** [comment]
- https://github.com/orgs/dlang-dockerized/packages
- https://hub.docker.com/u/dlangdockerized
