### ISSUE TITLE
Template engine

### ISSUE THREAD

**Issue by 0xEAB** [dlang-dockerized/packaging#8]
Should we use a template engine to generate image recipes?

**Comment by 0xEAB** [comment]
I doubt this could reduce the bloat in this repo for adding new images as we’d still want to store the generated Dockerfiles somewhere and pin versions together. E.g. there’s likely no good reason to build an image with future DMD 2.150 on an OS version from now. Also we don’t want to create a always growing matrix of *systems* × *compilers*.

**Comment by 0xEAB** [comment]
I particularly dislike the Bash and GNU/Busybox magic certain other Docker image repos use to generate their recipes.
I’d prefer to have a novice-readable script in Python or something. (Pero no hablo Python…)

**Comment by jnms-me** [comment]
j2 is probably the most well-known: https://pypi.org/project/Jinja2/.
I still would like generated dockerfiles to be committed or at least released.

**Comment by 0xEAB** [comment]
>  I still would like generated dockerfiles to be committed or at least released.

would it make sense to create a “release” branch that includes the CI/CD generated dockerfiles?

**Comment by jnms-me** [comment]
That makes sense yeah, should work nicely.

**Comment by 0xEAB** [comment]
Template engine:
Implemented by f877bc9511f545691fc696ea77232c2d422e3392 and a8c100e355fc6f352cdcd6542e5da68cd7af64a6.
